apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

replicas:
- name: guestbook
  count: 5  # ← STAGING = 5 replicas

images:
- name: paulbouwer/hello-kubernetes
  newTag: 1.9  # ← Version différente

namespace: staging
